---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore: [ master ]
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [ master ]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter PHP #
      ################################
      - name: Lint PHP code base
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PHP: true
          FILTER_REGEX_INCLUDE: .*app/*.php
          FILTER_REGEX_EXCLUDE: .*vendor/*
          OUTPUT_DETAILS: detailed
          OUTPUT_FORMAT: tap

      - name: artifact
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: reports
          path: "${{ github.workspace }}/super-linter.report"